Bootstrap:docker
From:centos:7

%labels
MAINTAINER singular55

%environment
	LANG=C.UTF-8
	# couldn't change LC_ALL on target
	#LC_ALL=C.UTF-8
	PATH=/bin_override:$PATH
	LIBRARY_PATH=/lib_override:$LIBRARY_PATH
	LD_LIBRARY_PATH=/lib_override:$LD_LIBRARY_PATH
	#WORKDIR=/work
	WRITEABLE=~/Container_Writeable
	#export LC_ALL LANG PATH LIBRARY_PATH LD_LIBRARY_PATH WORKDIR
	export LANG PATH LIBRARY_PATH LD_LIBRARY_PATH WRITEABLE

%setup
	mkdir -p $SINGULARITY_ROOTFS/lib_override
	mkdir -p $SINGULARITY_ROOTFS/bin_override
	#mkdir -p $SINGULARITY_ROOTFS/work

	wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2019-09/R/eclipse-jee-2019-09-R-linux-gtk-x86_64.tar.gz -O /tmp/eclipse.tar.gz
	tar -xf /tmp/eclipse.tar.gz -C $SINGULARITY_ROOTFS/bin_override
	rm /tmp/eclipse.tar.gz

	cp eclipse.ini $SINGULARITY_ROOTFS/bin_override/eclipse/

	## agraph
	# http://franz.com/ftp/pri/acl/ag/ag6.4.0/linuxamd64.64/agraph-6.4.0-linuxamd64.64.tar.gz
	wget http://franz.com/ftp/pri/acl/ag/ag6.4.0/linuxamd64.64/agraph-6.4.0-linuxamd64.64.tar.gz -O /tmp/agraph.tar.gz
	tar -xf /tmp/agraph.tar.gz -C $SINGULARITY_ROOTFS/bin_override
	rm /tmp/agraph.tar.gz

	## tomcat
	# https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz
	wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.47/bin/apache-tomcat-8.5.47.tar.gz -O /tmp/tomcat.tar.gz
	tar -xf /tmp/tomcat.tar.gz -C $SINGULARITY_ROOTFS/bin_override
	# Apache installed as u:root g:root with no group or other permissions.  For us to run apache from the 
	# container we need other permissions, it looks like.
	chmod -r o+rX $SINGULARITY_ROOTFS/bin_override/apache-tomcat-8.5.47
	rm /tmp/tomcat.tar.gz

	## mysql
	# https://dev.mysql.com/downloads/file/?id=495278 - login
	# https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.20-linux-glibc2.12-x86_64.tar.xz
	wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.20-linux-glibc2.12-x86_64.tar.xz -O /tmp/mysql.tar.xz
	tar -xf /tmp/mysql.tar.xz -C $SINGULARITY_ROOTFS/bin_override
	rm /tmp/mysql.tar.xz

	## lite mysql
	wget https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-8.0.20-linux-x86_64-minimal.tar.xz -O /tmp/mysql.tar.xz
	tar -xf /tmp/mysql.tar.xz -C $SINGULARITY_ROOTFS/bin_override
	rm /tmp/mysql.tar.xz



%post
	#yum --enablerepo=extras install -y epel-release
	yum -y install epel-release	
	yum repolist
	#yum update --fix-missing
	yum install -y git meld wget kdiff3

	# mysql uses libnuma
	yum install -y numactl-libs


	#yum clean

	#fix some X / DBus issues?
	dbus-uuidgen > /var/lib/dbus/machine-id

	#eclipse jee

	##wget http://ftp.osuosl.org/pub/eclipse/technology/epp/downloads/release/2019-09/R/eclipse-jee-2019-09-R-linux-gtk-x86_64.tar.gz -O /tmp/eclipse.tar.gz
	
	#tar -xf /tmp/eclipse.tar.gz -C /opt
	#tar -xf /tmp/eclipse.tar.gz -C ${SINGULARITY_ROOTFS}
	# ~ is /root for singularity hub
	
	##tar -xf /tmp/eclipse.tar.gz -C ~
	##rm /tmp/eclipse.tar.gz

	#moved from /opt/eclipse
	
	##cp eclipse.ini ~/eclipse/


%files
	#eclipse.ini /opt/eclipse/
	eclipse.ini eclipse.ini

%runscript
	#exec /bin/echo "Hi there, container runscript!"
	#exec /usr/bin/meld

	mkdir -p ${WRITEABLE}
	touch ${WRITEABLE}/HiThere

	/bin/echo "Config files should go in ${WRITEABLE}."


%apprun meld
	exec meld "$@"

%apprun eclipse
	exec /bin_override/eclipse/eclipse "$@"

%apprun kdiff3
	exec kdiff3 "$@"

